export const widgetInfo = {
  mangrove_net_change: {
    Title: 'Global extent of mangroves for select years from 1996 to 2016.',
    Overview: 'This data set was generated by Aberystwyth University and soloEO within the framework of the Global Mangrove Watch (GMW) project, which is a part of the Japan Aerospace Exploration Agency’s (JAXA) Kyoto & Carbon Initiative and the Mangrove Capital Africa Programme coordinated by Wetlands International and financed by DOB Ecology. The map (v2.0) depicts the global extent of mangrove forests for the year 2010, derived by Random Forest Classification of a combination of L-band radar (ALOS PALSAR) and optical (Landsat-5, -7) satellite data. All satellite data and software used to derive the GMW mangrove maps are available in the public domain. Approximately 15,000 Landsat scenes and 1,500 ALOS PALSAR (1 x 1 degree) mosaic tiles were used to create optical and radar image composites covering the coastlines along the tropical and sub-tropical coastlines in the Americas, Africa, Asia and Oceania. The classification was confined using a mangrove habitat mask, which defined regions where mangrove ecosystems can be expected to exist. The mangrove habitat definition was based on geographical parameters such as latitude, elevation and distance from ocean water. Training for the habitat mask and classification of the 2010 mangrove mask was based on randomly sampling 38 million points using the mangrove masks (for the year 2000) of Giri et al. (2011) and Spalding et al. (2010) and the water occurrence layer defined by Pekel et al. (2017). The data set is available for download at, http://data.unep-wcmc.org/datasets/45',
    Citation: 'Bunting P., Rosenqvist A., Lucas R., Rebelo L-M., Hilarides L., Thomas N., Hardy A., Itoh T., Shimada M. and Finlayson C.M. (2018). <a href=""https://www.mdpi.com/2072-4292/10/10/1669"" target=""_blank"">The Global Mangrove Watch – a New 2010 Global Baseline of Mangrove Extent.</a> Remote Sensing, 2018, 10, 1669; doi:10.3390/rs10101669',
    'Date of content': '1996, 2007, 2008, 2009, 2010, 2015, 2016',
    License: 'https://creativecommons.org/licenses/by/4.0/',
  },
  mangrove_coverage: {
    Title: 'Fraction of the coastline covered by mangrove forest',
    Overview: '**',
    Citation: '**',
    'Date of content': '1996, 2007, 2008, 2009, 2010, 2015, 2016',
    License: 'https://creativecommons.org/licenses/by/4.0/"',
  },
  mangrove_biomass: {
    Title: 'Global analysis of mangrove canopy height and aboveground carbon',
    Overview: '**',
    Citation: '**',
    'Date of content': '1996, 2007, 2008, 2009, 2010, 2015, 2016',
    License: '**',
  },
  mangrove_height: {
    Title: 'Global analysis of mangrove canopy height and aboveground carbon',
    Overview: '**',
    Citation: '',
    'Date of content': '1996, 2007, 2008, 2009, 2010, 2015, 2016',
    License: '',
  },
  mangrove_alerts: {
    Title: '',
    Overview: '',
    DataLink: '',
    Citation: '',
    'Date of content': '',
    License: '',
  },
  mangrove_hotspots: {
    Title: '',
    Overview: '',
    DataLink: '',
    Citation: '',
    'Date of content': '',
    License: '',
  },
  mangrove_activity: {
    Title: '',
    Overview: '',
    DataLink: '',
    Citation: '',
    'Date of content': '',
    License: '',
  }
};
